import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { z } from "zod";
import { Resend } from "resend";
import { createAuditLog } from "@/lib/audit";
import { buildVbtEmailHtml, escapeHtml, VBT_EMAIL } from "@/lib/email-templates";

const sendSchema = z.object({
  to: z.string().email("Invalid email address"),
  subject: z.string().optional(),
  message: z.string().optional(),
});

export async function POST(
  req: Request,
  { params }: { params: { id: string } }
) {
  const session = await getServerSession(authOptions);
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const user = session.user as any;
  if (["VIEWER"].includes(user.role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const body = await req.json();
  const parsed = sendSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0].message }, { status: 400 });
  }

  const quote = await prisma.quote.findFirst({
    where: { id: params.id, organizationId: (user as any).activeOrgId ?? user.orgId },
    include: { project: { include: { client: { select: { name: true } } } }, preparedByUser: { select: { fullName: true } } },
  });

  if (!quote) return NextResponse.json({ error: "Quote not found" }, { status: 404 });
  const quotedByName = (quote as { preparedByUser?: { fullName?: string } }).preparedByUser?.fullName ?? "VBT Team";

  // Generate PDF by calling our own PDF endpoint
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  let pdfBuffer: Buffer | null = null;

  try {
    const pdfRes = await fetch(`${appUrl}/api/quotes/${params.id}/pdf`, {
      headers: {
        Cookie: req.headers.get("Cookie") ?? "",
      },
    });

    if (pdfRes.ok) {
      const arrayBuffer = await pdfRes.arrayBuffer();
      pdfBuffer = Buffer.from(arrayBuffer);
    }
  } catch (pdfErr) {
    console.warn("PDF generation failed, sending without attachment:", pdfErr);
  }

  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json(
      { error: "Email service not configured. Set RESEND_API_KEY." },
      { status: 503 }
    );
  }

  const resend = new Resend(process.env.RESEND_API_KEY);
  const quoteNumber = (quote as { quoteNumber?: string }).quoteNumber ?? quote.id.slice(0, 8).toUpperCase();
  const projectName = (quote.project as { projectName?: string; name?: string }).projectName ?? (quote.project as { name?: string }).name ?? "";
  const clientName = (quote.project as { client?: { name: string } }).client?.name ?? "";
  const totalPrice = (quote as { totalPrice?: number }).totalPrice ?? 0;

  const subject =
    parsed.data.subject ??
    `VBT Quote ${quoteNumber} – ${projectName}`;

  const bodyHtml = `
    <h2 style="color: ${VBT_EMAIL.headerBg}; margin: 0 0 16px 0;">Quote ${escapeHtml(quoteNumber)}</h2>
    <p style="color: #666; font-size: 13px; margin: 0 0 16px 0;">Quoted by: ${escapeHtml(quotedByName)}</p>
    <table style="width: 100%; border-collapse: collapse;">
      <tr>
        <td style="padding: 8px 0; color: #666; width: 40%;">Project</td>
        <td style="padding: 8px 0; font-weight: bold;">${escapeHtml(projectName)}</td>
      </tr>
      ${clientName ? `<tr><td style="padding: 8px 0; color: #666;">Client</td><td style="padding: 8px 0; font-weight: bold;">${escapeHtml(clientName)}</td></tr>` : ""}
      <tr><td style="padding: 8px 0; color: #666;">Total</td><td style="padding: 8px 0; font-size: 20px; font-weight: bold; color: ${VBT_EMAIL.accent};">$${Number(totalPrice).toLocaleString("en-US", { minimumFractionDigits: 2 })}</td></tr>
    </table>
    ${parsed.data.message ? `<div style="margin-top: 16px; padding: 16px; background: white; border-radius: 4px; border-left: 3px solid ${VBT_EMAIL.headerBg};"><p style="margin: 0; color: #444;">${escapeHtml(parsed.data.message)}</p></div>` : ""}
  `.trim();
  const htmlBody = buildVbtEmailHtml({
    title: "Cost Quote",
    subtitle: "Vision Building Technologies",
    bodyHtml,
    footerText: "This quote was generated by the VBT Cotizador system.",
    attachmentDescription: pdfBuffer ? "Please find the detailed quote PDF attached to this email." : undefined,
  });

  try {
    const emailResult = await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL ?? "quotes@visionbuildingtechs.com",
      to: parsed.data.to,
      subject,
      html: htmlBody,
      attachments: pdfBuffer
        ? [
            {
              filename: `VBT-Quote-${quoteNumber}.pdf`,
              content: pdfBuffer,
            },
          ]
        : undefined,
    });

    await prisma.quote.update({
      where: { id: params.id },
      data: { status: "sent" },
    });

    if (quote.project?.id) {
      const proj = await prisma.project.findUnique({
        where: { id: quote.project.id },
        select: { status: true },
      });
      const s = proj?.status as string | undefined;
      if (s === "lead" || s === "qualified") {
        await prisma.project.update({
          where: { id: quote.project.id },
          data: { status: "quoting" },
        });
      }
    }

    await createAuditLog({
      orgId: (user as any).activeOrgId ?? user.orgId,
      userId: user.id,
      action: "quote_sent",
      entityType: "quote",
      entityId: params.id,
      meta: { to: parsed.data.to, quoteNumber },
    });

    return NextResponse.json({
      success: true,
      messageId: emailResult.data?.id,
    });
  } catch (emailErr: any) {
    console.error("Email send error:", emailErr);
    return NextResponse.json(
      { error: emailErr.message ?? "Failed to send email" },
      { status: 500 }
    );
  }
}
