import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { z } from "zod";
import { Resend } from "resend";
import { createAuditLog } from "@/lib/audit";

const sendSchema = z.object({
  to: z.string().email("Invalid email address"),
  subject: z.string().optional(),
  message: z.string().optional(),
});

export async function POST(
  req: Request,
  { params }: { params: { id: string } }
) {
  const session = await getServerSession(authOptions);
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const user = session.user as any;
  if (["VIEWER"].includes(user.role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const body = await req.json();
  const parsed = sendSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0].message }, { status: 400 });
  }

  const quote = await prisma.quote.findFirst({
    where: { id: params.id, orgId: user.orgId },
    include: { project: true, country: true },
  });

  if (!quote) return NextResponse.json({ error: "Quote not found" }, { status: 404 });

  // Generate PDF by calling our own PDF endpoint
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  let pdfBuffer: Buffer | null = null;

  try {
    const pdfRes = await fetch(`${appUrl}/api/quotes/${params.id}/pdf`, {
      headers: {
        Cookie: req.headers.get("Cookie") ?? "",
      },
    });

    if (pdfRes.ok) {
      const arrayBuffer = await pdfRes.arrayBuffer();
      pdfBuffer = Buffer.from(arrayBuffer);
    }
  } catch (pdfErr) {
    console.warn("PDF generation failed, sending without attachment:", pdfErr);
  }

  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json(
      { error: "Email service not configured. Set RESEND_API_KEY." },
      { status: 503 }
    );
  }

  const resend = new Resend(process.env.RESEND_API_KEY);
  const quoteNumber = quote.quoteNumber ?? quote.id.slice(0, 8).toUpperCase();

  const subject =
    parsed.data.subject ??
    `VBT Quote ${quoteNumber} – ${quote.project.name}`;

  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background-color: #1a3a5c; padding: 24px; border-radius: 8px 8px 0 0;">
        <h1 style="color: white; margin: 0; font-size: 24px;">Vision Building Technologies</h1>
        <p style="color: rgba(255,255,255,0.7); margin: 4px 0 0 0; font-size: 14px;">Cost Quote</p>
      </div>
      <div style="background-color: #f8f9fa; padding: 24px; border-radius: 0 0 8px 8px;">
        <h2 style="color: #1a3a5c; margin: 0 0 16px 0;">Quote ${quoteNumber}</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 0; color: #666; width: 40%;">Project</td>
            <td style="padding: 8px 0; font-weight: bold;">${quote.project.name}</td>
          </tr>
          ${quote.project.client ? `<tr><td style="padding: 8px 0; color: #666;">Client</td><td style="padding: 8px 0; font-weight: bold;">${quote.project.client}</td></tr>` : ""}
          ${quote.country ? `<tr><td style="padding: 8px 0; color: #666;">Destination</td><td style="padding: 8px 0; font-weight: bold;">${quote.country.name}</td></tr>` : ""}
          <tr><td style="padding: 8px 0; color: #666;">Landed/DDP Total</td><td style="padding: 8px 0; font-size: 20px; font-weight: bold; color: #e87722;">$${quote.landedDdpUsd.toLocaleString("en-US", { minimumFractionDigits: 2 })}</td></tr>
        </table>
        ${parsed.data.message ? `<div style="margin-top: 16px; padding: 16px; background: white; border-radius: 4px; border-left: 3px solid #1a3a5c;"><p style="margin: 0; color: #444;">${parsed.data.message}</p></div>` : ""}
        ${pdfBuffer ? "<p style='color: #666; font-size: 14px; margin-top: 24px;'>Please find the detailed quote PDF attached to this email.</p>" : ""}
        <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid #e0e0e0;">
          <p style="color: #999; font-size: 12px; margin: 0;">This quote was generated by the VBT Cotizador system.</p>
        </div>
      </div>
    </div>
  `;

  try {
    const emailResult = await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL ?? "quotes@visionbuildingtechs.com",
      to: parsed.data.to,
      subject,
      html: htmlBody,
      attachments: pdfBuffer
        ? [
            {
              filename: `VBT-Quote-${quoteNumber}.pdf`,
              content: pdfBuffer,
            },
          ]
        : undefined,
    });

    // Save QuoteDoc record
    await prisma.quoteDoc.create({
      data: {
        quoteId: params.id,
        type: "EMAIL",
        emailTo: parsed.data.to,
        emailMessageId: emailResult.data?.id,
        meta: { subject },
      },
    });

    // Update quote status
    await prisma.quote.update({
      where: { id: params.id },
      data: {
        status: "SENT",
        sentAt: new Date(),
        sentTo: parsed.data.to,
      },
    });

    await createAuditLog({
      orgId: user.orgId,
      userId: user.id,
      action: "QUOTE_SENT",
      entityType: "Quote",
      entityId: params.id,
      meta: { to: parsed.data.to, quoteNumber },
    });

    return NextResponse.json({
      success: true,
      messageId: emailResult.data?.id,
    });
  } catch (emailErr: any) {
    console.error("Email send error:", emailErr);
    return NextResponse.json(
      { error: emailErr.message ?? "Failed to send email" },
      { status: 500 }
    );
  }
}
